language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install -r test_requirements.txt
# before_script:
#   - pip install -r test_requirements.txt --use-mirrors
#   - git clone https://github.com:paulsievers/python_tests.git
#   - cd python_tests
#   - git checkout -qf 17b8119796516195527dcb4f454a2ebd41d60244
#   - py.test example/tests.py --cov=example
#   - cd -
script:
  - pytest
# after_success:
#   - coveralls
